### ISSUE TITLE
would it will update to compatible with a new tensorflow version 

### ISSUE THREAD

**Issue by SeekPoint** [abhipec/fnet#1]
tf0.10.0r cannot be install by pip

**Comment by abhipec** [comment]
Hi @loveJasmine 

I have a code that is compatible with TensorFlow 1.8 version. It is available at https://github.com/abhipec/FgEC

The model related code is available in the following sub directory: https://github.com/abhipec/FgEC/tree/master/src/baselines/fnet 

However there are minor difference and it misses instructions to run. 

May be later next week I can merge these two repo.

**Comment by SeekPoint** [comment]
great, expecting...

**Comment by abhipec** [comment]
I have updated the repository. Now the code available at https://github.com/abhipec/FgEC supports TensorFlow 1.10
